### ISSUE TITLE
False positive for image used for logo or favicon

### ISSUE THREAD

**Issue by rei-vilo** [wilhelmer/mkdocs-unused-files#2]
`mkdocs.yml` uses `img/Cat_Icon.png` as logo and favicon.

```
theme:
    logo: img/Cat_Icon.png
    favicon: img/Cat_Icon.png
```

However, `img/Cat_Icon.png` is flagged as unused:

```
INFO     -  The following files exist in the docs directory, but may be unused:
              - img/Cat_Icon.png
```

Below the minimal example updated with logo and favicon

[Minimal_example_with_favicon.zip](https://github.com/wilhelmer/mkdocs-unused-files/files/10238014/Minimal_example_with_favicon.zip)

**Comment by wilhelmer** [comment]
This is working as intended. The plugin only searches in the page content, not in the rendered template (footer, header, navigation), for better performance.

The [htmlproofer](https://github.com/manuzhang/mkdocs-htmlproofer-plugin) also doesn't do this by default, also because of performance reasons:  

> This defaults to off because it is much slower and often redundant to repeat for every single page.

However, they have a `validate_rendered_template` option to explicitly turn this on. I might add a similar option in the future.

**Comment by rei-vilo** [comment]
Thank you for the explanations. I am closing the ticket.

**Comment by wilhelmer** [comment]
I've added a note to the Readme for clarification.
