### ISSUE TITLE
Had failures after install - bs4 is also required

### ISSUE THREAD

**Issue by Dario503** [wilhelmer/mkdocs-unused-files#7]
Installing with pip3.11 / python3.11. `mkdocs serve` fails with several errors.  Went back and installed bs4, now mkdocs running. Might want to mention this dependency in your installation info.  Also, pip complains about bs4 missing 'pyproject.toml' and the 'wheel' package... Thanks.

**Comment by wilhelmer** [comment]
Thanks for reporting! I just made the following changes:

* Added bs4 dependency (6e895afd242992d9d6f0bb4038c5f442e5a94316)
* Added info message that the plugin is disabled when `mkdocs serve` is used (fbf8c2cf699f1ef6c84b9e6ba38e363e01dc9d62)

The issue with pip complaining about the wheel package must be fixed in bs4, I guess.
